### ISSUE TITLE
Redirects to localhost

### ISSUE THREAD

**Issue by naisanza** [harvard-itsecurity/docker-misp#10]
Port 80 redirects to localhost. 

When running in a container orchestrator, it will fail. Port 80 shouldn't redirect to localhost

**Comment by ventz** [comment]
@naisanza See step #3 in the install -- it only defaults to "localhost" if you don't set the MISP_FQDN. This is so that people can quickly test it.

If you change "MISP_FQDN", it will be available on that FQDN and the cert (self-generated) will be generated for that FQDN (you can override that too by providing valid certs).

Port 80 by default binds to the "real" port tcp/80 on the server you are running docker from, so if you are on the server itself, localhost will always open tcp/80 to itself. However, if you provide the MISP_FQDN and the FQDN is binded to the IP of the docker host that you ran the container from, it will open the FQDN on port 80.

Does this make sense?

**Comment by naisanza** [comment]
@ventz ah gotcha that makes sense, I'll give that a try

**Comment by ventz** [comment]
@naisanza Ok - closing this, but if you run into any issues, please reply here/ping me and i'll re-open it + investigate.
