### ISSUE TITLE
Instantiating an instance fails

### ISSUE THREAD

**Issue by dmoore44** [harvard-itsecurity/docker-misp#46]
Following the directions, I cloned the git repo and made the appropriate changes to build.sh, then ran build.sh. The image appeared in my images cache, so I proceeded with initializing the database with `docker run -it --rm -v /docker/misp-db:/var/lib/mysql harvarditsecurity/misp /init-db`, but am met with the following:

> chown: changing ownership of '/var/lib/mysql': Operation not permitted
> chown: changing ownership of '/var/lib/mysql': Operation not permitted
> Cannot change ownership of the database directories to the 'mysql'
> user.  Check that you have the necessary permissions and try again.
> chown: changing ownership of '/var/lib/mysql': Operation not permitted
> 200123 05:35:56 mysqld_safe Logging to syslog.
> 200123 05:35:56 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
> ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")
> ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")
> ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")
> ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")
> ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")
> ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")
> ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")
> ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")
> ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")
> touch: cannot touch '/var/lib/mysql/.db_initialized': Permission denied
> chown: changing ownership of '/var/lib/mysql': Operation not permitted

This is all being run on Docker for Mac.

**Comment by ventz** [comment]
@dmoore44 It's one of a couple of "filesystem" issues:

(apple/mac specific)
1.) The folder you are mounting needs to be added to the `Preferences -> File Sharing` option on the Mac Docker engine.

2.) As of a few recent versions - apple disallowed apps to write to the `/` (root) dir -- so you may have to create something like `/Users/$youruser/docker` instead of `/docker`.

3.) The directory is created as root/narrow permissions and Docker can't write to it -- this is easily solved by removing it and then re-creating empty with your username. You can debug it by getting an interactive shell within docker and creating a file to see what the container user ID translates to within your system.

**Comment by ventz** [comment]
Assuming you are all set. Re-open if it's still an issue.
