### ISSUE TITLE
Error in Dockerfile line 136

### ISSUE THREAD

**Issue by gaglimax** [harvard-itsecurity/docker-misp#50]
Hello !

In Dockerfile, line 136 is :
`tar zxvf ssdeep-2.14.1.tar.gz && cd ssdeep-2.14.1.tar.gz && ./configure && make && sudo make install ; \`
and shourld be :
`tar zxvf ssdeep-2.14.1.tar.gz && cd ssdeep-2.14.1 && ./configure && make && sudo make install ; \`
Else, command `cd` fails.

**Comment by ventz** [comment]
@gaglimax Thanks - fixed - will push out in a few.

We had this fixed a while back (it was reported here: https://github.com/MISP/docker-misp/pull/14) and the problem was that it was merged into the mirrored fork instead of the maintained source (here).

I've also added a note to ISSUES/PRs there that all of the development happens here so it doesn't happen again.
